apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-loki
  namespace: openshift-logging
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: obc-loki
  storageClassName: openshift-storage.noobaa.io
